using DiagnosticApiDemo.HostingStartups;
using DiagnosticCore;
using ElasticSearchCore;
using LocalizerAbstraction;
using MessageQueueAbstraction;
using Microsoft.AspNetCore.Hosting;
using MongodbCore;
using PersistenceAbstraction;

[assembly: HostingStartup(typeof(DiagnosticServiceStartup))]
[assembly: HostingStartup(typeof(ElasticSearchServiceStartup))]
[assembly: HostingStartup(typeof(LogMongodbServiceStartup))]
[assembly: HostingStartup(typeof(PersistenceStartup))]
[assembly: HostingStartup(typeof(MongodbLocalizerStartup))]
[assembly: HostingStartup(typeof(ApiVersioningStartup))]
[assembly: HostingStartup(typeof(RabbitmqServiceStartup))]
[assembly: HostingStartup(typeof(RedisServiceStartup))]
[assembly: HostingStartup(typeof(SwaggerStartup))]
[assembly: HostingStartup(typeof(CorsStartup))]
[assembly: HostingStartup(typeof(FreeSqlStartup))]
[assembly: HostingStartup(typeof(HangfireStartup))]
[assembly: HostingStartup(typeof(SpiderStartup))]
[assembly: HostingStartup(typeof(MiniProfilerStartup))]
[assembly: HostingStartup(typeof(FeignStartup))]